### PR TITLE
Fix for ie

### PR DESCRIPTION
**Pull request by spdavid**
This should fix IE. Needs to be tested with a full build.  target had to be downgraded to es5.  and I modified the code a bit on the index.html. Plus added the pollyfills for IE. 

Option 2.. Scrap this and tell people to use chrome or any other modern browser.

### CODE REVIEW

**Comment by marcus-sonestedt** [comment]
I manually deployed this to the to test site. 

Got this in IE, "ReferenceError: 'AbortController' is undefined". Chrome works.

I actually planned to just have the site detect IE and say "please use a modern browser", rather than a bunch of errors. Given that we have some IE support now, adding that might not be too hard, or?

**Comment by spdavid** [comment]
I added a pollyfill for abort controller.. Might do the trick. cant know for sure unless its a production build. 

In my opinion we should show the message.. "User Modern Browser". I can fix that.

**Comment by marcus-sonestedt** [comment]
Sounds good. Add that message instead.

Den sön 10 maj 2020 kl 23:14 skrev David Opdendries <
notifications@github.com>:

**Comment by marcus-sonestedt** [comment]
Closing this then. Waiting for new PR on message.

**Pull request closed without merging**
